
spring:
  main:
    web-application-type: none
  batch:
    job:
      enabled: false  # 自動的なジョブ実行を無効化
    jdbc:
      initialize-schema: always  # Spring Batchのメタデータテーブルを自動作成
      isolation-level-for-create: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
