spring:
  main:
    web-application-type: none
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

logging:
  level:
    root: INFO
    org.springframework.batch: DEBUG
